package dmit2015.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;
import lombok.Data;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.io.Serializable;
import java.time.LocalDateTime;

@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name = "aircraft")
public class Aircraft implements Serializable {

    @Id                 // This is the primary key field
    @GeneratedValue(strategy = GenerationType.IDENTITY)     // This primary key field is generated by the database
    private Long id;

    @Column(length = 20, nullable = false)
    @NotBlank(message = "The Model field is required.")
    @Size(min = 3, max = 20, message = "The field Model must be a string with a minimum length of {min} and a maximum length of {max}.")
    private String model;

    @Column(length = 20, nullable = false)
    @NotBlank(message = "The Manufacturer field is required.")
    @Size(min = 3, max = 20, message = "The field Manufacturer must be a string with a minimum length of {min} and a maximum length of {max}.")
    private String manufacturer;

    @Column(length = 6, nullable = false)
    @NotBlank(message = "The TailNumber field is required.")
    @Size(min = 2, max = 6, message = "The TailNumber must be a string with a minimum length of {min} and a maximum length of {max}.")
    @Pattern(regexp = "^[A-Z][0-9]{1,5}[A-Z]{0,2}$", message = "The field TailNumber must match the regular expression '^[A-Z][0-9]{1,5}[A-Z]{0,2}$'.")
    private String tailNumber;

    @Version
    private Integer version;

    @Column(nullable = false)
    private LocalDateTime createTime;

    private LocalDateTime updateTime;

    @PrePersist
    private void beforePersist() {
        createTime = LocalDateTime.now();
    }

    @PreUpdate
    private void beforeUpdate() {
        updateTime = LocalDateTime.now();
    }

    public Aircraft(Long id, String manufacturer, String model, String tailNumber) {
        this.id = id;
        this.manufacturer = manufacturer;
        this.model = model;
        this.tailNumber = tailNumber;
    }
}
