### Get all Phones
GET http://localhost:8181/restapi/PhonesDto

### Get a single Phones with an id of 1
GET http://localhost:8181/restapi/PhonesDto/3

### POST a new Phone with valid data
POST http://localhost:8181/restapi/PhonesDto
Content-Type: application/json
#Authorization: Bearer {{dlee_token}}
Authorization: Bearer {{sking_token}}

{
  "name": "iPhone 13 Pro",
  "date": "2023-10-10",
  "price": "1500",
  "brand": "Apple",
  "operatingSystem": "iOS"
}

### Post a new Phone with invalid data
POST http://localhost:8181/restapi/PhonesDto
Content-Type: application/json

{
  "model": "iPhone 15 Pro",
  "releaseDate": "2023-10-10",
  "price": "1500",
  "brand": " ",
  "operatingSystem": "iOS"
}

### Get a single Phone with an id of 3
GET http://localhost:8181/restapi/PhonesDto/3

### Update Phone with an id of 3 with valid data
PUT http://localhost:8181/restapi/PhonesDto/4
Content-Type: application/json
#Authorization: Bearer {{dlee_token}}
Authorization: Bearer {{sking_token}}

{
  "id": 4,
  "name": "iPhone 14 Pro",
  "date": "2023-10-10",
  "price": "1500",
  "brand": "Apple",
  "operatingSystem": "iOS",
  "version": 0
}

### Delete an Phone with an id of 3
DELETE http://localhost:8181/restapi/PhonesDto/3
#Authorization: Bearer {{dlee_token}}
Authorization: Bearer {{sking_token}}